name: "CI"
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/flake-checker-action@main

    - name: Check Nix formatting
      run: nix flake check --no-build
      
  module-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    
    - name: Run standalone home-manager tests
      run: nix-build tests/home-manager-standalone-test.nix -A all
      
    - name: Run NixOS home-manager tests
      run: nix-build tests/nixos-home-manager-test.nix -A all
