name: "CI"
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/flake-checker-action@main

    - name: Check Nix formatting
      run: nix flake check --no-build
